name: Deploy AWS Infrastructure
on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}  
  ENVIRONMENT: dev  
  TERRAFORM_VERSION: 1.7.0  

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: terraform.tfstate

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
          TF_VAR_env: ${{ env.ENVIRONMENT }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
          TF_VAR_env: ${{ env.ENVIRONMENT }}
