name: Deploy AWS Infrastructure
on:
  push:
    branches: [ "main" ]
env:
  AWS_REGION: ap-south-1
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}  
  env: 'dev'  
  TERRAFORM_VERSION: 1.7.0  


jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: terraform.tfstate

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_project_name: ${{ vars.PROJECT_NAME }}
          TF_VAR_env: ${{ vars.env }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_project_name: ${{ vars.PROJECT_NAME }}
          TF_VAR_env: ${{ vars.env }}
        